CREATE OR REPLACE TABLE FACT_GESTION (
  ID_GESTION        INTEGER NOT NULL,
  ID_OPERACION      INTEGER NOT NULL,
  ID_TIEMPO         INTEGER NOT NULL,
  TIPO_CONTACTO     STRING NOT NULL,
  RESULTADO_GESTION STRING NOT NULL,
  IMPORTE_PROMESA   NUMBER(18,2),
  FECHA_PROMESA     DATE,
  ID_OPERADOR       STRING NOT NULL
);

CREATE OR REPLACE TABLE FACT_PAGO (
  ID_PAGO      INTEGER NOT NULL,
  ID_OPERACION INTEGER NOT NULL,
  ID_TIEMPO    INTEGER NOT NULL,
  MONTO_PAGO   NUMBER(18,2) NOT NULL,
  CANAL_PAGO   STRING NOT NULL
);
