COPY INTO DIM_TIEMPO
FROM @STG_RECUPERO/dim_tiempo.csv
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1);

COPY INTO DIM_AGENCIA
FROM @STG_RECUPERO/dim_agencia.csv
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1);

COPY INTO DIM_OPERACION
FROM @STG_RECUPERO/dim_operacion.csv
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1);

COPY INTO FACT_GESTION
FROM @STG_RECUPERO/fact_gestion.csv
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1);

COPY INTO FACT_PAGO
FROM @STG_RECUPERO/fact_pago.csv
FILE_FORMAT = (TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1);
