CREATE OR REPLACE VIEW VW_STOCK_AGENCIA AS
SELECT
    o.ID_AGENCIA,
    a.NOMBRE_AGENCIA,
    a.REGION,
    SUM(o.SALDO_INICIAL) AS SALDO_INICIAL_AGENCIA,
    SUM(o.SALDO_ACTUAL)  AS SALDO_ACTUAL_AGENCIA
FROM DIM_OPERACION o
JOIN DIM_AGENCIA a ON o.ID_AGENCIA = a.ID_AGENCIA
GROUP BY o.ID_AGENCIA, a.NOMBRE_AGENCIA, a.REGION;

CREATE OR REPLACE VIEW VW_RECUPERO_MENSUAL_AGENCIA AS
SELECT
    t.ANIO,
    t.MES,
    t.NOMBRE_MES,
    o.ID_AGENCIA,
    a.NOMBRE_AGENCIA,
    a.REGION,
    SUM(p.MONTO_PAGO) AS MONTO_RECUPERADO
FROM FACT_PAGO p
JOIN DIM_OPERACION o ON p.ID_OPERACION = o.ID_OPERACION
JOIN DIM_TIEMPO t     ON p.ID_TIEMPO = t.ID_TIEMPO
JOIN DIM_AGENCIA a    ON o.ID_AGENCIA = a.ID_AGENCIA
GROUP BY t.ANIO, t.MES, t.NOMBRE_MES, o.ID_AGENCIA, a.NOMBRE_AGENCIA, a.REGION;
