CREATE OR REPLACE VIEW VW_GESTIONES_MENSUAL_AGENCIA AS
SELECT
    t.ANIO,
    t.MES,
    t.NOMBRE_MES,
    o.ID_AGENCIA,
    a.NOMBRE_AGENCIA,
    a.REGION,
    COUNT(*) AS GESTIONES_TOTALES,
    SUM(CASE WHEN g.RESULTADO_GESTION IN ('Contacto efectivo','Promesa de pago')
             THEN 1 ELSE 0 END) AS GESTIONES_CONTACTO,
    SUM(CASE WHEN g.RESULTADO_GESTION = 'Promesa de pago'
             THEN 1 ELSE 0 END) AS GESTIONES_PROMESA,
    SUM(CASE WHEN g.RESULTADO_GESTION IN ('Contacto efectivo','Promesa de pago')
             THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0) AS TASA_CONTACTABILIDAD,
    SUM(CASE WHEN g.RESULTADO_GESTION = 'Promesa de pago'
             THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0) AS PORC_GESTIONES_CON_PROMESA
FROM FACT_GESTION g
JOIN DIM_OPERACION o ON g.ID_OPERACION = o.ID_OPERACION
JOIN DIM_TIEMPO t     ON g.ID_TIEMPO = t.ID_TIEMPO
JOIN DIM_AGENCIA a    ON o.ID_AGENCIA = a.ID_AGENCIA
GROUP BY 1,2,3,4,5,6;
