CREATE OR REPLACE VIEW VW_DASH_AGENCIA_MENSUAL AS
SELECT
    e.ANIO,
    e.MES,
    e.NOMBRE_MES,
    e.ID_AGENCIA,
    e.NOMBRE_AGENCIA,
    e.REGION,
    e.SALDO_INICIAL_AGENCIA,
    e.SALDO_ACTUAL_AGENCIA,
    e.MONTO_RECUPERADO,
    e.EFICIENCIA_SOBRE_INICIAL,
    g.GESTIONES_TOTALES,
    g.GESTIONES_CONTACTO,
    g.GESTIONES_PROMESA,
    g.TASA_CONTACTABILIDAD,
    g.PORC_GESTIONES_CON_PROMESA
FROM VW_EFICIENCIA_MENSUAL_AGENCIA e
LEFT JOIN VW_GESTIONES_MENSUAL_AGENCIA g
  ON e.ANIO = g.ANIO
 AND e.MES = g.MES
 AND e.ID_AGENCIA = g.ID_AGENCIA;
